language: ruby
dist: xenial
rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.0
  - 2.4.1
  - 2.5.1
  - 2.6
  - jruby
matrix:
  include:
    - rvm: 1.8.7
      dist: trusty
      gemfile: Gemfile.rails3
    - rvm: 1.8.7
      dist: trusty
      gemfile: Gemfile.rails3_rmagick
    - rvm: 1.8.7
      dist: trusty
      gemfile: Gemfile.rbpdf-font
    - rvm: 1.9.2
      dist: trusty
      gemfile: Gemfile.rails3
    - rvm: 1.9.2
      dist: trusty
      gemfile: Gemfile.rails3_rmagick
    - rvm: 1.9.2
      dist: trusty
      gemfile: Gemfile.rbpdf-font
    - rvm: 1.9.3
      dist: trusty
      gemfile: Gemfile.rails3
    - rvm: 1.9.3
      dist: trusty
      gemfile: Gemfile.rails3_rmagick
    - rvm: 1.9.3
      dist: trusty
      gemfile: Gemfile.rails4
    - rvm: 1.9.3
      dist: trusty
      gemfile: Gemfile.rails4_rmagick
    - rvm: 1.9.3
      dist: trusty
      gemfile: Gemfile.rbpdf-font
  exclude:
    - rvm: 2.0
      gemfile: Gemfile.rails5
    - rvm: 2.0
      gemfile: Gemfile.rails5_rmagick
    - rvm: 2.0
      gemfile: Gemfile.rails5_mini_magick
    - rvm: 2.1
      gemfile: Gemfile.rails5
    - rvm: 2.1
      gemfile: Gemfile.rails5_rmagick
    - rvm: 2.1
      gemfile: Gemfile.rails5_mini_magick
    - rvm: 2.5.1
      gemfile: Gemfile.rails3
    - rvm: 2.5.1
      gemfile: Gemfile.rails3_rmagick
    - rvm: 2.5.1
      gemfile: Gemfile.rails4
    - rvm: 2.5.1
      gemfile: Gemfile.rails4_rmagick
    - rvm: 2.6
      gemfile: Gemfile.rails3
    - rvm: 2.6
      gemfile: Gemfile.rails3_rmagick
    - rvm: 2.6
      gemfile: Gemfile.rails4
    - rvm: 2.6
      gemfile: Gemfile.rails4_rmagick
    - rvm: jruby
      gemfile: Gemfile.rails3_rmagick
    - rvm: jruby
      gemfile: Gemfile.rails4_rmagick
    - rvm: jruby
      gemfile: Gemfile.rails5_rmagick
    - rvm: jruby
      gemfile: Gemfile.rails5_mini_magick
before_install:
  - gem update bundler
install:
  - bundle install
script:
  - if [[ "$BUNDLE_GEMFILE" =~ rbpdf-font$ ]]; then cd rbpdf-font && bundle exec rake test ; else bundle exec rake test ; fi
gemfile:
  - Gemfile.rails3
  - Gemfile.rails3_rmagick
  - Gemfile.rails4
  - Gemfile.rails4_rmagick
  - Gemfile.rails5
  - Gemfile.rails5_rmagick
  - Gemfile.rails5_mini_magick
  - Gemfile.rbpdf-font
notifications:
  email: false
